[build]
  publish = "."
  command = "npm run build || echo skipping-build"

[dev]
  command = "npm run serve"
  port = 8080

[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"
